---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  #hosts: all
  require_ansible_repo: true
  #require_ansible_omnibus: false
  ansible_verbose: false
  ansible_version: latest
  ansible_verbosity: 1
  ansible_diff: true
  group_vars_path: ./host_vars
  role_path: ~/.ansible/roles
  playbook: couchdb.yml

platforms:
  - name: ubuntu-18.04
    driver:
      box: ubuntu/bionic64
      provider: virtualbox
suites:
  - name: couchdb
    provisioner:
      hosts: couchdb
      playbook: couchdb.yml
    driver:
      synced_folders:
        - ["~/couchdb", "/var/www/couchdb", 'create: true, owner: "www-data", group: "www-data"',mount_options: [\"dmode=775,fmode=664\"]]
      network:
        - ["private_network", {ip: "192.168.30.153"}]
