all:
  children:
    izar:
      hosts:

          couchdb:
            ansible_ssh_host: 192.168.30.153
            ansible_ssh_user: vagrant
            ansible_ssh_pass: vagrant
            ansible_ssh_port: 22
            ip: 192.168.30.153
