Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "ubuntu/bionic64"
  c.vm.hostname = "couchdb-ubuntu-1804.vagrantup.com"
  c.vm.network(:private_network, {:ip=>"192.168.30.153"})
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.synced_folder "/home/mouad/couchdb", "/var/www/couchdb", create: true, owner: "www-data", group: "www-data"
  c.vm.provider :virtualbox do |p|
    p.name = "kitchen-couchdb_role-couchdb-ubuntu-1804"
    p.customize ["modifyvm", :id, "--audio", "none"]
  end
end
